##### 1) Load the Iris dataset as a list of lists (each of the 150 lists should have 5 elements). Compute and print the mean and the standard deviation for each of the 4 measurement columns (i.e. sepal length and width, petal length and width). Compute and print the mean and the standard deviation for each of the 4 measurement columns, separately for each of the three Iris species (Versicolor, Virginica and Setose). Which measurement would you consider “best”, if you were to guess the Iris species based only on those four values? 

In [ ]:
import pandas as pd


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Dataset/Data-Science lab/Iris.csv")

In [ ]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
#df.shape,df.columns

In [ ]:
df["Species"].value_counts()

Iris-setosa        50
Iris-virginica     50
Iris-versicolor    50
Name: Species, dtype: int64

In [ ]:
print("sepal_length mean and Deviation is ", df["SepalLengthCm"].mean(),df["SepalLengthCm"].std())


sepal_length mean and Deviation is  5.843333333333335 0.8280661279778629


In [ ]:
print("sepal_width mean and Deviation is ", df["SepalWidthCm"].mean(),df["SepalWidthCm"].std())
    

sepal_width mean and Deviation is  3.0540000000000007 0.4335943113621737


In [ ]:
print("petal_length mean and Deviation is ", df["PetalLengthCm"].mean(),df["PetalLengthCm"].std())

petal_length mean and Deviation is  3.7586666666666693 1.7644204199522617


In [ ]:
print("petal_length mean and Deviation is ", df["PetalWidthCm"].mean(),df["PetalWidthCm"].std())

petal_length mean and Deviation is  1.1986666666666672 0.7631607417008414


In [ ]:
 df[df['Species']=="Iris-versicolor"].mean()

Id               75.500
SepalLengthCm     5.936
SepalWidthCm      2.770
PetalLengthCm     4.260
PetalWidthCm      1.326
dtype: float64

In [ ]:
 df[df['Species']=="Iris-setosa"].mean()

Id               25.500
SepalLengthCm     5.006
SepalWidthCm      3.418
PetalLengthCm     1.464
PetalWidthCm      0.244
dtype: float64

In [ ]:
 df[df['Species']=="Iris-virginica"].mean()

Id               125.500
SepalLengthCm      6.588
SepalWidthCm       2.974
PetalLengthCm      5.552
PetalWidthCm       2.026
dtype: float64

# Exp-5 to split data into train and test

In [ ]:
#train_data=df.sample(frac=.8)

In [ ]:
#train_data["species"].value_counts()

In [ ]:
#test_data=df.loc[~df.index.isin(train_data.index)]

In [ ]:
#test_data["species"].value_counts()

In [ ]:
df1=df.drop("Id",axis=1)

In [ ]:
df1.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
from sklearn.model_selection import train_test_split
train,test= train_test_split(df1,test_size=0.2)

In [ ]:
len(train),len(test)

(120, 30)

In [ ]:
train.head(10)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
11             4.8           3.4            1.6           0.2      Iris-setosa
7              5.0           3.4            1.5           0.2      Iris-setosa
80             5.5           2.4            3.8           1.1  Iris-versicolor
82             5.8           2.7            3.9           1.2  Iris-versicolor
5              5.4           3.9            1.7           0.4      Iris-setosa
103            6.3           2.9            5.6           1.8   Iris-virginica
44             5.1           3.8            1.9           0.4      Iris-setosa
135            7.7           3.0            6.1           2.3   Iris-virginica
142            5.8           2.7            5.1           1.9   Iris-virginica
48             5.3           3.7            1.5           0.2      Iris-setosa

In [ ]:
train["Species"].value_counts()

Iris-setosa        41
Iris-virginica     40
Iris-versicolor    39
Name: Species, dtype: int64

In [ ]:
test["Species"].value_counts()

Iris-versicolor    11
Iris-virginica     10
Iris-setosa         9
Name: Species, dtype: int64

In [ ]:
train.to_csv('/content/drive/MyDrive/Dataset/Data-Science lab/Iries_train_data.csv',index=False)
test.to_csv('/content/drive/MyDrive/Dataset/Data-Science lab/Iries_test_data.csv',index=False)

In [ ]:
train_df = pd.read_csv("/content/drive/MyDrive/Dataset/Data-Science lab/Iries_train_data.csv")
test_df= pd.read_csv("/content/drive/MyDrive/Dataset/Data-Science lab/Iries_test_data.csv")

In [ ]:
train_df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0            4.8           3.4            1.6           0.2      Iris-setosa
1            5.0           3.4            1.5           0.2      Iris-setosa
2            5.5           2.4            3.8           1.1  Iris-versicolor
3            5.8           2.7            3.9           1.2  Iris-versicolor
4            5.4           3.9            1.7           0.4      Iris-setosa

In [ ]:
# how many missing values are there Train data?
train_df.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
#what is the propotion of "sertosa" in test dataset?
sertosa_count=test_df[test_df["Species"]=="Iris-setosa"].value_counts().sum()
#print("propotion of sertosa in test dataset", )

## What is the accuracy score of the K-Nearest Neighbor model (model_1) with 2/3 neighbors using Train_Data and Test_Data? 

In [1]:
from sklearn.neighbors import KNeighborsClassifier 
knn=KNeighborsClassifier(n_neighbors=2)

In [2]:
x_train=train_df.drop('Species',axis=1)
y_train=train_df["Species"]
x_test=test_df.drop('Species',axis=1)
y_test=test_df["Species"]

NameError: ignored

In [ ]:
x_train.head()

In [ ]:
y_train.head()

In [ ]:
x_test[:5]

In [ ]:
knn.fit(x_train,y_train)# training phase 

In [ ]:
score=knn.score(x_test,y_test)
score

In [ ]:
pred=knn.predict(x_test)
pred

In [ ]:
y_test

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [ ]:
print(confusion_matrix(y_test,pred))

In [ ]:
print(classification_report(y_test,pred))

## Build a logistic regression model (model_2) keeping the modelling steps constant. Find the accuracy of the model_2 

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model2=LogisticRegression()

In [ ]:
model2.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
pred=model2.predict(x_test)

In [ ]:
pred

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [ ]:
accuracy_score(y_test,pred)

1.0

In [ ]:
confusion_matrix(y_test,pred)

array([[ 9,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 10]])

In [ ]:
print(classification_report(y_test,pred))


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      1.00      1.00        11
 Iris-virginica       1.00      1.00      1.00        10

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



## Exp-7 :Demonstrate Decision tree classification model and Evaluate the performance of classifier on Iris

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf=DecisionTreeClassifier(max_depth=3,random_state=42)

In [ ]:
clf.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=42, splitter='best')

In [ ]:
pred=clf.predict(x_test)
pred

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [ ]:
confusion_matrix(y_test,pred)

array([[ 9,  0,  0],
       [ 0, 10,  1],
       [ 0,  0, 10]])

In [ ]:
accuracy_score(y_test,pred)

0.9666666666666667

In [ ]:
print(classification_report(y_test,pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      0.88      0.93         8
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        30
      macro avg       0.97      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30



# Demonstrate any of the Clustering model and Evaluate the performance on Iris dataset. 

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
km=KMeans(n_clusters=3)

In [ ]:
km.fit(x_train,y_train)

KMeans(n_clusters=3)

In [ ]:
km.labels_[:10]

array([1, 2, 2, 1, 1, 0, 0, 1, 0, 0])

In [ ]:
pred=km.predict(x_test)

In [ ]:
pred[:10]

array([2, 0, 1, 1, 2, 0, 2, 2, 2, 1])

In [ ]:
km.cluster_centers_

array([[4.98684211, 3.4       , 1.48157895, 0.24473684],
       [5.898     , 2.726     , 4.36      , 1.42      ],
       [6.85      , 3.075     , 5.684375  , 2.021875  ]])

In [ ]:
y_test

100     Iris-virginica
36         Iris-setosa
65     Iris-versicolor
90     Iris-versicolor
137     Iris-virginica
28         Iris-setosa
102     Iris-virginica
109     Iris-virginica
135     Iris-virginica
91     Iris-versicolor
127     Iris-virginica
26         Iris-setosa
89     Iris-versicolor
21         Iris-setosa
39         Iris-setosa
140     Iris-virginica
41         Iris-setosa
13         Iris-setosa
108     Iris-virginica
59     Iris-versicolor
138     Iris-virginica
83     Iris-versicolor
35         Iris-setosa
55     Iris-versicolor
5          Iris-setosa
121     Iris-virginica
4          Iris-setosa
32         Iris-setosa
33         Iris-setosa
94     Iris-versicolor
Name: species, dtype: object

In [ ]:
from sklearn import datasets

In [ ]:
iris=datasets.load_iris()

In [ ]:
iris

In [ ]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [ ]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
km=KMeans(n_clusters=3)

In [ ]:
km.fit(iris.data,iris.target)

KMeans(n_clusters=3)

In [ ]:
km.cluster_centers_

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [ ]:
km.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [ ]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
import numpy as np


In [ ]:
pred=np.choose(km.labels_,[1,0,2]).astype(np.int64)

In [ ]:
confusion_matrix(pred,iris.target)

array([[50,  0,  0],
       [ 0, 48, 14],
       [ 0,  2, 36]], dtype=int64)

In [ ]:
accuracy_score(iris.target,pred)

0.8933333333333333